version: '3.8'

services:
  eventhubs:
    container_name: "eventhubs"
    image: "mcr.microsoft.com/azure-messaging/eventhubs-emulator:latest"
    volumes:
      - "${CONFIG_PATH}:/Eventhubs_Emulator/ConfigFiles/Config.json"
    ports:
      - "5672:5672"
    environment:
      BLOB_SERVER: azurite
      METADATA_SERVER: azurite
      ACCEPT_EULA: ${ACCEPT_EULA}
    depends_on:
      - azurite
    networks:
      eh-emulator:
        aliases:
          - "eventhubs"
  azurite:
    container_name: "azurite"
    image: "mcr.microsoft.com/azure-storage/azurite:latest"
    volumes:
      - "${INFRA_PATH}/StorageAccount/.ssl/127.0.0.1.pem:/.ssl/127.0.0.1.pem"
      - "${INFRA_PATH}/StorageAccount/.ssl/127.0.0.1-key.pem:/.ssl/127.0.0.1-key.pem"
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    networks:
      eh-emulator:
        aliases:
          - "azurite"
    # command: "azurite --oauth basic --cert /.ssl/127.0.0.1.pem --key /.ssl/127.0.0.1-key.pem"
  cosmosdb:
    container_name: "cosmosdb"
    image: "mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest"
    ports:
      - "8081:8081"
      - "10250-10255:10250-10255"
    environment:
      - AZURE_COSMOS_EMULATOR_IP_ADDRESS_OVERRIDE=127.0.0.1
    networks:
      cosmosdb-emulator:
        aliases:
          - "cosmosdb"
  kusto:
    container_name: "kusto"
    image: "mcr.microsoft.com/azuredataexplorer/kustainer-linux:latest"
    ports:
      - "8080:8080"
    environment:
      ACCEPT_EULA: ${ACCEPT_EULA}
networks:
  eh-emulator:
  cosmosdb-emulator:
  kusto: